DROP DATABASE IF EXISTS maxc_dev_localhost;

CREATE DATABASE maxc_dev_localhost;
USE maxc_dev_localhost;
CREATE TABLE IF NOT EXISTS User (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	Name VARCHAR(32) NOT NULL, 
	Email TEXT(2083) NOT NULL,
	Password VARCHAR(32) NOT NULL,
	PhoneNumber VARCHAR(12) NOT NULL DEFAULT '0'
);

CREATE TABLE IF NOT EXISTS Brand (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS Item (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	Name VARCHAR(64) NOT NULL, 
	OriginalPrice DOUBLE DEFAULT 0 NOT NULL,
    ReleaseDate DATE DEFAULT CURRENT_TIMESTAMP(0),
    Category ENUM('Tops') DEFAULT('Tops') NOT NULL,
    Gender ENUM('Male', 'Female', 'Unisex') DEFAULT 'Unisex' NOT NULL,
    BrandID INT DEFAULT 0 NOT NULL,
    CONSTRAINT `fk_item_brand`
		FOREIGN KEY (BrandID) REFERENCES Brand (ID)
		ON DELETE RESTRICT
		ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Material (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(32)
);

CREATE TABLE IF NOT EXISTS LinkItemMaterial (
	ItemID INT NOT NULL,
	MaterialID INT NOT NULL,
	Ratio INT DEFAULT 0 NOT NULL,
    PRIMARY KEY (ItemID, MaterialID),
    CONSTRAINT `fk_item_link`
		FOREIGN KEY (ItemID) REFERENCES Item (ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
    CONSTRAINT `fk_material_link`
		FOREIGN KEY (MaterialID) REFERENCES Material (ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

INSERT INTO Brand (Name) VALUES ("Armani"), ("Tommy Hilfiger");
INSERT INTO Item (Name, OriginalPrice, BrandID) VALUES ("Hoodie", 56.98, 1);
INSERT INTO Item (Name, OriginalPrice, BrandID) VALUES ("Tshirt", 46.98, 2);

SELECT * FROM Item, Brand;